### ISSUE TITLE
Maybe drop Xemacs support

### ISSUE THREAD

**Issue by tarsius** [stardiviner/spice-mode#3]
Do you still intend to keep this compatible with Xemacs? It does not appear to be maintained anymore, for example its homepage www.xemacs.org has been down for a while now.

If not, then you could remove the `func-menu` stuff, leading to fewer warnings when compiling with GNU Emacs.

Thanks for considering.

**Comment by stardiviner** [comment]
@tarsius  I just put the author's code on github. So PR is welcome. I will accept it.
